### ISSUE TITLE
Uncaught TypeError: (0 , import_crypto.randomFillSync) is not a function

### ISSUE THREAD

**Issue by mrfullset** [Darginec05/Yoopta-Editor#118]
I've installed a `v2.0.1` (last stable release I suppose?) to a clear Vite react project. At first, I've got an error from https://github.com/Darginec05/Yoopta-Editor/issues/98 and followed steps in the provided StackOverflow answer. But next I got this error `chunk-TKG5BUZS.js?v=84badda5:11555 Uncaught TypeError: (0 , import_crypto.randomFillSync) is not a function` in a browser console. I've used the [code from README](https://github.com/Darginec05/Yoopta-Editor?tab=readme-ov-file#plugins).

**To Reproduce**
1. Make a new Vite react project (no TypeScript)
2. `yarn add slate slate-react @yoopta/editor@2.0.1 @yoopta/paragraph@2.0.1`
3. `yarn dev`
4. Check console in browser

**Expected behavior**
An editor appears

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Browser: Arc (Chromium)
 - Version: 2.0.1

**Comment by Darginec05** [comment]
Hi @mrfullset. 
Thanks for reporting issue! 

This issue happens because `nanoid` package. 
It seems problem in `vite` default configuration. 
Did you try this?  - https://stackoverflow.com/a/70719923/8847638  

--- 
However, I recommend you try to use new v4 (despite the fact that this version is in -rc) version with dropped `nanoid` packages and many cool features.
Demo with source code is available - https://stackblitz.com/edit/vitejs-vite-syjdcx?file=src%2FApp.tsx

**Comment by Darginec05** [comment]
I removed nanoid from core package. 
And I recommend you use v4.0.0

Check demos 
- https://yoopta-editor.vercel.app/examples/withBaseFullSetup

--- 
### Example for your case
Vite example - https://stackblitz.com/edit/vitejs-vite-syjdcx
