### ISSUE TITLE
[BUG] Markdown importer ignores MD Lists

### ISSUE THREAD

**Issue by colo-o** [Darginec05/Yoopta-Editor#304]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I have been testing the Markdown Importer and I found an issue when using MD Lists. Basically importer strips out MD lists wherever the list is located in MD content.

### Steps to Reproduce

To reproduce:

1. Go to https://yoopta.dev/examples/withExports/markdown
2. Type any MD list
3. Content disappear

### Environment

- OS: Any
- Browser: Any

### Screenshots

![image](https://github.com/user-attachments/assets/9f4c5cdc-794a-4010-bb96-f0cabb7ab67e)

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
@colo-o Thanks for reporting issue.
It's already done in last published `-rc` version - `4.7.1-rc.6`
You can check it demo link - https://yoopta-editor-csa0r6gaj-dargos-projects.vercel.app/examples/withExports/markdown

**Comment by angelkurten** [comment]
@Darginec05  I found an issue with the markdown functionality. When I create a nested list on the left panel, the formatting doesn't reflect correctly on the right panel. The nested items appear at the same level instead of maintaining the hierarchy.

![Captura de pantalla 2024-09-22 a la(s) 4 23 13 p m](https://github.com/user-attachments/assets/f42f9e8d-9d0b-4ace-bbda-61eab5f9ae80)

**Comment by Darginec05** [comment]
This issue can be closed because original problem was fixed in 4.8.0

@angelkurten could you create please new issue with this bug?
